name: projectshop
favicon: null
layout_spectrum: 0.92314
typography_spectrum: 0.40393
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ebe4d4'
    - '#2c0d08'
    - '#c8802b'
    - '#5c5751'
    - '#9a3a22'
  brandStrength: 0.1875
  lightness: 0.45777557301335037
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
